Health check
enigmampc/enigma-p2p pull request #258
Opened 2019-11-21 09:28 UTC by lenak25

2019-11-27 11:03 UTC, assafmo requested changes

2019-11-27 11:03 UTC, assafmo commented on src/worker/EnigmaNode.js
>    }
Please use promisify:
```javascript
const { promisify } = require("util");
// ...
connectToBootstrap(peerInfo) {
  const dial = promisify(dial).bind(this);
  try {
    const connection = await dial(peerInfo); // Notice that connection is unused
  } catch (connectionErr) {
    this._logger.error(`Failed connecting to a bootstrap node= ${connectionErr}`);
    return false;
  }

  this.notify(peerInfo);
  return true;
}
```

2019-11-27 11:03 UTC, assafmo commented on src/worker/EnigmaNode.js
>    }
Also Notice that `dial` can be implemented with `promisify` on `dialProtocol` and `node.dialProtocol`.  
This way you won't have to do `const dial = promisify(dial).bind(this);`.

2019-11-27 11:03 UTC, assafmo commented on src/worker/controller/NodeController.js
> +      let regParams = await this.asyncGetRegistrationParams();
let -> const

2019-11-27 11:03 UTC, assafmo commented on src/worker/controller/NodeController.js
> +        let eth = await this.ethereum().healthCheck();
let -> const

2019-11-27 11:03 UTC, assafmo commented on src/worker/controller/actions/HealthCheckAction.js
> +              let eth = await this._controller.ethereum().healthCheck();
const

2019-11-27 11:03 UTC, assafmo commented on src/worker/controller/actions/connectivity/BootstrapDiscoveredAction.js
> +    });
Please use `promisify` with `try/catch`.

2019-11-27 11:04 UTC, assafmo commented
@lenak25  You can ignore the "let -> const" comments, but please use promisify, it will greatly improve code readability. :pray:

2019-11-27 20:06 UTC, lenak25 commented
@assafmo , code review comments were integrated.. please review again :)

2019-11-28 07:54 UTC, assafmo submitted a review, later dismissed

2019-11-28 07:57 UTC, assafmo commented
@lenak25 re: https://github.com/enigmampc/enigma-p2p/issues/262. Please add basic documentation (`curl` examples should suffice for now).

2019-11-28 07:58 UTC, assafmo commented
Also "Merging is blocked" due to "The base branch requires all commits to be signed." :man_shrugging:

2019-12-01 10:47 UTC, assafmo approved these changes

2019-12-01 12:59 UTC, merged