Add connectivity status to health check
enigmampc/enigma-p2p pull request #283
Opened 2019-12-23 10:58 UTC by lenak25

2019-12-28 09:55 UTC, Cashmaney submitted a review, later dismissed

2019-12-29 10:07 UTC, assafmo requested changes

2019-12-29 10:07 UTC, assafmo commented on test/init_worker_test.js
> +    await testUtils.sleep(3000);
@lenak25  There is no other way to wait for the nodes to be ready?
This slows down the tests and may fail the test occasionally.

2019-12-29 10:07 UTC, assafmo commented on test/webserver_test.js
> +  let pPaths = peers.map(p => {
let -> const

2019-12-29 10:07 UTC, assafmo commented on test/webserver_test.js
> +  await bNodeController.shutdownSystem();
Do we need to `try/catch` these `await`s? If they throw the `resolve` at the end will never be called.

2019-12-29 10:07 UTC, assafmo commented on test/webserver_test.js
> +    let bNodeCoreServer = bNode.coreServer;
let -> const

2019-12-29 10:07 UTC, assafmo commented on test/webserver_test.js
> +    http.get({ hostname: "localhost", port: port, path: hcUrl }, res => {
Instead of `http.get` with callbacks, please use `axios.get` with `async/await`.

2019-12-29 10:07 UTC, assafmo commented on test/webserver_test.js
> +        http.get({ hostname: "localhost", port: port, path: statusUrl }, async res => {
Instead of `http.get` with callbacks, please use `axios.get` with `async/await`.

2019-12-29 10:07 UTC, assafmo commented on test/webserver_test.js
> +    http.get({ hostname: "localhost", port: port, path: hcUrl }, res => {
This will also eliminate `res.on`, `res.end`, etc.

2019-12-29 10:07 UTC, assafmo commented on test/webserver_test.js
> +        http.get({ hostname: "localhost", port: port, path: statusUrl }, async res => {
This will also eliminate `res.on`, `res.end`, etc.

2019-12-29 10:07 UTC, assafmo commented on test/webserver_test.js
> +            await stopTest(peers, bNodeController, bNodeCoreServer, resolve);
`stopTest` should be inside an `after` or an `afterEach` function, in case this line will never be reached.

2019-12-29 10:07 UTC, assafmo commented on src/worker/controller/actions/GetStatusAction.js
> +        workerParams = await this._controller.asyncExecCmd(C.GET_ETH_WORKER_PARAM);
`workerParams` can be a `const` defined inside of the `try` clause (it's never used elsewhere).

2019-12-29 13:58 UTC, assafmo submitted a review, later dismissed

2019-12-29 14:26 UTC, assafmo approved these changes
:+1:

2019-12-30 07:48 UTC, merged